Connect api
Chike1990/bookstore pull request #2
Opened 2021-10-01 16:13 UTC by Chike1990

In this Milestone, I used store, actions and reducers in React and connected an existing API via Redux and use the data to display something in a UI.

2021-10-01 16:37 UTC, helman101 commented
#STATUS: INVALID 🔴 ⚠️ 

Hi, @Chike1990, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors, please remember that all the linters should be in green when you send the code review request 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2021-10-01 17:04 UTC, GzimAsani requested changes
# Hi @Chike1990  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good use of gitflow :+1: 

## Required Changes ♻️
- [ ] After I add or remove a book and refresh the page the books that I have created disappear. This shows that the changes are not going through because the saves should persist. Please take a step back and check your reducers
- [x] Even though the linters are green in github, but when I tried to open your app I saw a bunch of required changes by linters. Kindly see the pic below: ![Screenshot from 2021-10-01 19-00-17](https://user-images.githubusercontent.com/62705947/135659330-3c05054c-3205-48fb-bdf5-21cc01e0b5ad.png)
_Check the comments under the review for more information._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-01 17:04 UTC, GzimAsani commented on package.json
>    "dependencies": {
- [ ] You have used axios, but axios is not part of your dependencies, please add that otherwise the project will not function

2021-10-01 17:04 UTC, GzimAsani commented on src/components/Books.jsx
> +
- [ ] Please remove the commented code.

2021-10-02 17:42 UTC, barackm approved these changes
Hi @Chike1990, 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Cheers and Happy coding!👏👏👏

- [ ] [OPTIONAL] Kindly let's remove the warnings from the console after adding a new book 👍 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-02 17:45 UTC, Chike1990 commented
Thanks a lot

2021-12-07 11:47 UTC, merged