Add remove/feature
Chike1990/bookstore pull request #3
Opened 2021-10-01 16:24 UTC by Chike1990

In this Milestone, I connected React and Redux; and added add and remove functionalities to the app.

2021-10-01 18:05 UTC, wandji20 requested changes
Hello, @Chike1990  :raised_hands: 
-----
Great :muscle:  job :raised_hands:  implementing most of the requirements for this project.
However, there are a few issues you need to address to have this project approved.
## To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Very descriptive commit messages and pull request summary
:heavy_check_mark: Add and remove book functionalities :100: 

## Status: Require Changes :recycle: :red_circle: 
Please check the comments below and under the review and make all required changes.
Optional comments are not required to mark this project approved
- [ ] It will be nice to ignore all files that are not relevant to run this project(eg .lintrc, .stylelintrc.json, .hintrc, .eslintrc.json etc).


**Happy coding :computer:** 
**_Do not hesitate to make comments in this PR in case of doubts._**
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-01 18:05 UTC, wandji20 commented on src/redux/configureStore.js
> +  // additional reducers could be added here
- [x] It will be better to remove commented codes from your codebase

2021-10-01 18:05 UTC, wandji20 commented on src/components/Books.jsx
> +        </select>
- [ optional ] It will be more semantic to wrap these inputs in a `form` tag

2021-10-01 18:05 UTC, wandji20 commented on src/components/Books.jsx
> +  console.log(id)
- [ ] It will be nice to remove console statements from your codebase.

2021-10-01 18:05 UTC, wandji20 commented on src/components/Books.jsx
> +const Books = () => {
- [ ] One input is omitted for the book. It will b nice to add a local state for `author` alongside its `input` field with a corresponding `onChange` handler.

2021-10-01 18:05 UTC, wandji20 commented on src/components/Books.jsx
> +  ]);
- [ ] It will be nice to access the books from the redux store since it's in sync with this component and so will cause a rerender whenever the list of books is updated.

2021-10-02 08:36 UTC, Chike1990 commented on src/components/Books.jsx
> +const Books = () => {
There is only one input. The other for the **category** is already implemented. Thanks

2021-10-02 08:49 UTC, mke2111 approved these changes
### Hi @Chike1990, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 11:49 UTC, closed without merging